
# training
train			= true
sample			= true
image_dir               = ""
feature_dir		= ""
schedule_sampler        = "uniform"
lr                      = 1e-4
weight_decay            = 0.0
lr_anneal_steps         = 0
batch_size              = 1
microbatch              = -1        # -1 disables microbatches
ema_rate                = "0.9999"  # comma-separated list of EMA values
log_interval            = 10
save_interval           = 10000
resume_checkpoint       = ""
use_fp16                = false
fp16_scale_growth       = 1e-3
seed 			= 0

# architecture
[architecture]
image_size              = 64
num_channels            = 128
num_res_blocks          = 2
num_heads               = 4
num_heads_upsample      = -1
# num_head_channels     = -1
attention_resolutions   = "16,8"
# channel_mult          = ""
dropout                 = 0.0
class_cond              = false
# use_checkpoint        = false
# resblock_updown         = false
learn_sigma		= false
sigma_small		= false
diffusion_steps		= 1000
noise_schedule		= "linear"
timestep_respacing	= ""
use_kl			= false
predict_xstart		= false
rescale_timesteps	= true
rescale_learned_sigmas	= true
use_scale_shift_norm    = true
# use_fp16                = false
# use_new_attention_order = false
