
device = "cuda:0"
# mnist_dir = "./xyz/res/mnist"
imagenet_dir = "../sparse_autoencoder/res/imagenet"
feature_dir = "../sparse_autoencoder/run/1ae3fe65"
image_size = 64
n_channels = 3

train = []

[[eval]]
model_path = "./run/f2a2e4ac/model/epoch-39.pth"

diffusion_steps = 400
hidden_size = 128
num_generations = 8

# Leave feature_ids empty for all features.
feature_ids = []
centile_edits = [0, 1]
# 2 data points per label starting with 0
data_ids = [1]
