device = "cuda:0"
debug = false

[[train]]
# mnist_dir = "./xyz/res/mnist"
# tiny_imagenet_dir = "../sparse_autoencoder/res/tiny-imagenet-200"
imagenet_dir = "../sparse_autoencoder/res/imagenet"

# mnist
# feature_dir = "../sparse_autoencoder/run/171d21f725b8721bc98f2d334b103d6b0e83570a958c461866fd12c6280a670f"
# tiny imagenet
# feature_dir = "../sparse_autoencoder/run/2cc590d4"
# imagenet
feature_dir = "../sparse_autoencoder/run/1ae3fe65"

image_size = 64

epochs = 23
batch_size = 64
diffusion_steps = 400
hidden_size = 128
lr = 1e-4

# Consider leaving the drop_prob at 0 or at 1 / feature_size.
# I think the code assumes that features that are all zero are unconditional,
# but I don't want to make that assumption.
drop_prob = 0.0
